# Generated by Django 4.2.7 on 2023-12-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_student_user_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Co',
            field=models.CharField(choices=[('class1', 'class1'), ('class2', 'class2'), ('class3', 'class3'), ('class4', 'class4'), ('class5', 'class5'), ('class6', 'class6'), ('class7', 'class7'), ('class8', 'class8'), ('class9', 'class9'), ('class10', 'class10')], max_length=10),
        ),
    ]
